name: My First Workflow
on: push
jobs:
   first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
    - name: Welcome message
      run: |
       echo "My First github actions Job"
       ld -ltra
       cat README.md

 #   - name: List Files
 #     run: ls

 #   - name: Read file
 #     run: cat README.md
      